language: ruby

rvm: # the Ruby versions to be used
  - 2.1.0

env:
  global:
    - secure: "inAI4890H8/YDwAzn+dsQI0XFqfJ0VhZ1cjjXTcluyglPO8SwywVfDlDsRBGSWXsdC/4J1DFAIZnKxw04uwTnY87W03Xa3J5VyjpqNxvMyRfK1nJH/wXzCmn+G/GLNyqDlJo169NQZqzwnhDddHXG8R/XcK+8oz8XUx1ihmJiHE="

branches:
  only:
    - dev
    - master

before_install:
  - sudo apt-get install openjdk-7-jdk
  - java -version
  - mvn -version
  - phantomjs --version

script:
  - rake travis:test
  - rake travis:deploy

notifications:
  email:
    - api@edmunds.com
    - ielshareef@edmunds.com
    - jnaylor@edmunds.com
    - mbock@edmunds.com
    - yauhen_yemelyanau@epam.com
    - maksim_dadzerkin@epam.com
    - ihar_krupenin@epam.com
