language: ruby

rvm: # the Ruby versions to be used
  - 2.0.0

before_install:
  - gem update
  - gem install jekyll
  - gem install cucumber
  - gem install rspec
  - gem install capybara
  - gem install poltergeist
  - phantomjs --version

before_script:
  - rake local

script:
  - rake test

notifications:
  email:
    - vera_kruhliakova@epam.com
    - maksim_dadzerkin@epam.com